CREATE SEQUENCE SEQ_USUARIO_CH     START WITH 6  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PATIO_CH       START WITH 6  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MOTO_CH        START WITH 9  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POS_CH         START WITH 10 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MARCADOR_F_CH  START WITH 16 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MARCADOR_M_CH  START WITH 6  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEDICAO_CH     START WITH 26 INCREMENT BY 1 NOCACHE NOCYCLE;